### ISSUE TITLE
Error with examples

### ISSUE THREAD

**Issue by 2ant** [RajKKapadia/Google-Image-Downloader-Python#1]
Hi, i got some errors with both examples 

```Python
Traceback (most recent call last):
  File "I:\Python\pythonlearning\Image_Collector.py", line 150, in <module>
    1
  File "I:\Python\pythonlearning\Image_Collector.py", line 45, in download_google_images
    value="//input[contains(@class,'gLFyf gsfi')]"
  File "C:\Panda3D-1.10.10-x64\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 831, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Panda3D-1.10.10-x64\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Panda3D-1.10.10-x64\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[contains(@class,'gLFyf gsfi')]"}
  (Session info: chrome=112.0.5615.138)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x011CDCE3+50899]
	(No symbol) [0x0115E111]
	(No symbol) [0x01065588]
	(No symbol) [0x010908F9]
	(No symbol) [0x01090AFB]
	(No symbol) [0x010BF902]
	(No symbol) [0x010AB944]
	(No symbol) [0x010BE01C]
	(No symbol) [0x010AB6F6]
	(No symbol) [0x01087708]
	(No symbol) [0x0108886D]
	GetHandleVerifier [0x01433EAE+2566302]
	GetHandleVerifier [0x014692B1+2784417]
	GetHandleVerifier [0x0146327C+2759788]
	GetHandleVerifier [0x01265740+672048]
	(No symbol) [0x01168872]
	(No symbol) [0x011641C8]
	(No symbol) [0x011642AB]
	(No symbol) [0x011571B7]
	BaseThreadInitThunk [0x758F0099+25]
	RtlGetAppContainerNamedObjectPath [0x77A87B6E+286]
	RtlGetAppContainerNamedObjectPath [0x77A87B3E+238]
```

**Comment by Niharrrrrr** [comment]
Did you find any solution for this?

**Comment by Niharrrrrr** [comment]
@2ant you will have to update the class by checking the latest class from google. Do inspect element in google and edit the class from that
